// --- Coordenadas dos marcadores ---
const marcadores = [
  { x: 3484, y: 4498, nome: "<b>Mercado sombrio</b> (Mestre das missões diárias)", tipo: "mercado", link: "https://sangriafalls.com/mercado-sombrio/" },
  { x: 1211, y: 2293, nome: "<b>Shemhazai</b> - A Essência da Luminância", tipo: "conquista", icone: 'icons/shemhazai.svg', link: "https://sangriafalls.com/a-essencia-da-luminancia/" },
  { x: 2587, y: 3175, nome: "<b>Rathma</b> - Filho de Thanatos", tipo: "conquista", icone: 'icons/rathma.svg', link: "https://sangriafalls.com/filho-de-thanatos/" },
  { x: 4930, y: 2370, nome: "<b>Chefe Mundial</b> (WB)", tipo: "wb", link: "https://sangriafalls.com/boss-mundial/" },
  { x: 4547, y: 2926, nome: "<b>Chefe Mundial</b> (WB)", tipo: "wb", link: "https://sangriafalls.com/boss-mundial/" },
  { x: 4105, y: 3725, nome: "<b>Piracema</b> (Todos os dias às 19:30)", tipo: "eventos", icone: "icons/fish.svg", link: "https://sangriafalls.com/piracema/" },
  { x: 3679, y: 4255, nome: "Coliseu PVP ⚔️", tipo: "eventos", icone: "icons/coliseu.svg" },
  { x: 3293, y: 3920, nome: "<b>Classe:</b> Noctarin", tipo: "noctarin", link: "https://sangriafalls.com/noctarin/" },
  { x: 3138, y: 3640, nome: "<b>Evolução:</b> Noctarin", tipo: "noctarin", link: "https://sangriafalls.com/noctarin/" },
  { x: 4730, y: 3525, nome: "<b>Classe:</b> Mortak", tipo: "mortak", link: "https://sangriafalls.com/mortak/" },
  { x: 982, y: 2815, nome: "<b>Evolução:</b> Mortak", tipo: "mortak", link: "https://sangriafalls.com/mortak/" },
  { x: 3120, y: 4105, nome: "<b>Classe:</b> Sepulkros", tipo: "sepulkros", link: "https://sangriafalls.com/sepulkros/" },
  { x: 3945, y: 5175, nome: "<b>Evolução:</b> Sepulkros", tipo: "sepulkros", link: "https://sangriafalls.com/sepulkros/" },
  { x: 1260, y: 2700, nome: "<b>Classe:</b> Bastien", tipo: "bastien", link: "https://sangriafalls.com/bastien/" },
  { x: 1525, y: 2735, nome: "<b>Evolução:</b> Bastien", tipo: "bastien", link: "https://sangriafalls.com/bastien/" },
  { x: 3780, y: 2655, nome: "<b>Classe:</b> Draekhar", tipo: "draekhar", link: "https://sangriafalls.com/draekhar/" },
  { x: 4263, y: 1190, nome: "<b>Evolução:</b> Draekhar", tipo: "draekhar", link: "https://sangriafalls.com/draekhar/" },
  { x: 4232, y: 1490, nome: "<b>Classe:</b> Skarn", tipo: "skarn", link: "https://sangriafalls.com/skarn/" },
  { x: 2414, y: 1430, nome: "<b>Evolução:</b> Skarn", tipo: "skarn", link: "https://sangriafalls.com/skarn/" },
  { x: 2996, y: 1010, nome: "<b>Classe:</b> Carmesyne", tipo: "carmesyne", link: "https://sangriafalls.com/carmesyne/" },
  { x: 2193, y: 1150, nome: "<b>Evolução:</b> Carmesyne", tipo: "carmesyne", link: "https://sangriafalls.com/carmesyne/" },
  { x: 3257, y: 3153, nome: "<b>Evolução:</b> Umbrellis", tipo: "umbrellis", link: "https://sangriafalls.com/umbrellis/" },
  { x: 1060, y: 1410, nome: "<b>Classe:</b> Umbrellis", tipo: "umbrellis", link: "https://sangriafalls.com/umbrellis/" },
  { x: 5394, y: 2465, nome: "<b>Invasão</b> Solarus - Solarus", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 4331, y: 2975, nome: "<b>Invasão</b> Solarus - Azariel", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 640, y: 1415, nome: "<b>Invasão</b> Solarus - Raziel", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 4485, y: 2286, nome: "<b>Invasão</b> Megara - Jakira", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 936, y: 2880, nome: "<b>Invasão</b> Megara - Stravos", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 973, y: 1850, nome: "<b>Invasão</b> Drácula - Cassius", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 1252, y: 2811, nome: "<b>Invasão</b> Drácula - Valencia", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 2724, y: 4535, nome: "<b>Invasão</b> Drácula - Drácula", tipo: "invasao", icone: 'icons/invasao.svg', link: "https://sangriafalls.com/invasoes/" },
  { x: 2760, y: 4670, nome: "Alfa, o Lobo Branco (1)", tipo: "chefes", ato: 1 },
  { x: 3124, y: 4219, nome: "Alfa, o Lobo Branco (2)", tipo: "chefes", ato: 1 },
  { x: 3292, y: 4530, nome: "Alfa, o Lobo Branco (3)", tipo: "chefes", ato: 1 },
  { x: 3710, y: 4005, nome: "Keely, a Arqueira Gélida", tipo: "chefes", ato: 1 },
  { x: 2663, y: 4250, nome: "Errol, o Quebra-Pedras", tipo: "chefes", ato: 1 },
  { x: 3326, y: 4400, nome: "Rufus, o Capataz", tipo: "chefes", ato: 1 },
  { x: 3505, y: 4332, nome: "Lidia, a Arqueira do Caos", tipo: "chefes", ato: 1 },
  { x: 2650, y: 4760, nome: "Goreswine, o Devastador", tipo: "chefes", ato: 1 },
  { x: 2397, y: 4105, nome: "Grayson, o Armeiro", tipo: "chefes", ato: 1 },
  { x: 1743, y: 3715, nome: "Polora, a Caminhante Feérica", tipo: "chefes", ato: 1 },
  { x: 3044, y: 3945, nome: "Nicolau, o Caído", tipo: "chefes", ato: 1 },
  { x: 2977, y: 3745, nome: "Quincey, o Rei dos Bandidos", tipo: "chefes", ato: 1 },
  { x: 4326, y: 4325, nome: "Kodia, a Ursa Feroz", tipo: "chefes", ato: 1 },
  { x: 4108, y: 3725, nome: "Finn, o Pescador", tipo: "chefes", ato: 1 },
  { x: 4398, y: 3975, nome: "Talzur, o Horror Alado", tipo: "chefes", ato: 4 },
  { x: 1500, y: 4350, nome: "Clive, o Incendiário", tipo: "chefes", ato: 1 },
  { x: 2850, y: 4335, nome: "Tristan, o Caçador de Vampiros", tipo: "chefes", ato: 2 },
  { x: 3019, y: 4899, nome: "Nibbles, o Rato Pútrido", tipo: "chefes", ato: 1 },
  { x: 3650, y: 3050, nome: "Beatrice, a Costureira", tipo: "chefes", ato: 2 },
  { x: 3583, y: 2950, nome: "Christina, a Sacerdotisa do Sol", tipo: "chefes", ato: 2 },
  { x: 3112, y: 2935, nome: "Vincent, o Portador do Gelo", tipo: "chefes", ato: 2 },
  { x: 2124, y: 3050, nome: "Sir Erwin, o Cavaleiro Galante", tipo: "chefes", ato: 2 },
  { x: 2481, y: 2695, nome: "Raziel, o Pastor", tipo: "chefes", ato: 2 },
  { x: 2465, y: 2380, nome: "Terah, a Geomante", tipo: "chefes", ato: 2 },
  { x: 3024, y: 3420, nome: "Kriig, o General dos Mortos-Vivos", tipo: "chefes", ato: 2 },
  { x: 2966, y: 3127, nome: "Meredith, a Arqueira Brilhante", tipo: "chefes", ato: 2 },
  { x: 3327, y: 2330, nome: "Octavian, o Capitão da Milícia", tipo: "chefes", ato: 2 },
  { x: 3396, y: 2060, nome: "Leandra, a Sacerdotisa das Sombras", tipo: "chefes", ato: 2 },
  { x: 3756, y: 2320, nome: "Gaius, o Campeão Amaldiçoado", tipo: "chefes", ato: 2 },
  { x: 4024, y: 2300, nome: "Maja, a Sábia das Trevas", tipo: "chefes", ato: 2 },
  { x: 2810, y: 3014, nome: "Bane, o Lâmina Sombria", tipo: "chefes", ato: 2 },
  { x: 2868, y: 2842, nome: "Jade, a Caçadora de Vampiros", tipo: "chefes", ato: 2 },
  { x: 2303, y: 2009, nome: "Grethel, a Sopradora de Vidro", tipo: "chefes", ato: 2 },
  { x: 2980, y: 1889, nome: "Lorde Styx, o Campeão da Noite", tipo: "chefes", ato: 4 },
  { x: 3669, y: 1776, nome: "Willfred, o Ancião da Aldeia", tipo: "chefes", ato: 3 },
  { x: 4363, y: 3403, nome: "Frostmaw, o Terror da Montanha", tipo: "chefes", ato: 2 },
  { x: 4636, y: 3700, nome: "Terrorclaw, o Ogro", tipo: "chefes", ato: 4 },
  { x: 1795, y: 3061, nome: "Mairwyn, a Elementalista", tipo: "chefes", ato: 4 },
  { x: 1839, y: 2730, nome: "Solarus, o Imaculado", tipo: "chefes", ato: 4 },
  { x: 1350, y: 2845, nome: "Barão du Bouchon, o Sommelier", tipo: "chefes", ato: 4 },
  { x: 768, y: 2742, nome: "Azariel, o Arauto do Sol", tipo: "chefes", ato: 4 },
  { x: 1420, y: 3120, nome: "Morian, a Matriarca das Stormwing", tipo: "chefes", ato: 4 },
  { x: 1107, y: 2463, nome: "Sir Magnus, o Supervisor", tipo: "chefes", ato: 4 },
  { x: 752, y: 1465, nome: "Stravos, o Entalhador", tipo: "chefes", ato: 4 },
  { x: 975, y: 1460, nome: "Lucile, a Alquimista Venenosa", tipo: "chefes", ato: 4 },
  { x: 1045, y: 800, nome: "Dantos, o Mestre da Forja", tipo: "chefes", ato: 4 },
  { x: 1420, y: 726, nome: "Megara, a Rainha Serpente", tipo: "chefes", ato: 4 },
  { x: 2157, y: 1199, nome: "Henry Blackbrew, o Doutor", tipo: "chefes", ato: 4 },
  { x: 2755, y: 739, nome: "Voltatia, a Mestre da Energia", tipo: "chefes", ato: 4 },
  { x: 2295, y: 1304, nome: "Angram, o Purificador", tipo: "chefes", ato: 3 },
  { x: 2358, y: 1614, nome: "Domina, a Dançarina das Lâminas", tipo: "chefes", ato: 3 },
  { x: 3045, y: 1053, nome: "Ziva, a Engenheira", tipo: "chefes", ato: 3 },
  { x: 3643, y: 1209, nome: "Ungora, a Aranha Rainha", tipo: "chefes", ato: 3 },
  { x: 3905, y: 770, nome: "Albert, o Duque de Balaton", tipo: "chefes", ato: 3 },
  { x: 4403, y: 1305, nome: "Ben, o Velho Andarilho", tipo: "chefes", ato: 3 },
  { x: 4243, y: 1093, nome: "Cyril, o Ferreiro Amaldiçoado", tipo: "chefes", ato: 3 },
  { x: 4391, y: 1100, nome: "Matka, a Tecelã de Maldições", tipo: "chefes", ato: 4 },
  { x: 4535, y: 1444, nome: "Foulrot, o Devorador de Almas", tipo: "chefes", ato: 3 },
  { x: 4364, y: 1508, nome: "Gorecrusher, o Colosso", tipo: "chefes", ato: 4 },
  { x: 4697, y: 1993, nome: "General Valencia, a Depravada", tipo: "chefes", ato: 4 },
  { x: 4732, y: 2747, nome: "General Elena, a Desprezível", tipo: "chefes", ato: 2 },
  { x: 4759, y: 2260, nome: "General Cassius, o Traidor", tipo: "chefes", ato: 2 },
  { x: 1561, y: 3783, nome: "Simon Belmont, o Caçador de Vampiros", tipo: "chefes", ato: 4 },
  { x: 2050, y: 588, nome: "Adam, O Primogênito", tipo: "chefes", ato: 4 },
  { x: 5637, y: 2470, nome: "Drácula, o Rei Imortal", tipo: "chefes", ato: 4 },
  { x: 1412, y: 1120, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 1558, y: 3713, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 1051, y: 3115, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 1585, y: 2323, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2945, y: 3868, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2316, y: 4222, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2136, y: 4956, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3482, y: 4452, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3924, y: 3971, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3980, y: 4919, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3551, y: 3391, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2523, y: 3375, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2459, y: 2565, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3464, y: 2639, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 4899, y: 2312, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 4365, y: 2198, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 4434, y: 2765, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2668, y: 1862, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 4675, y: 1378, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 3790, y: 1538, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 2580, y: 1002, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 1959, y: 1651, nome: "Portal de Vampiro", tipo: "teleporte"},
  { x: 830, y: 1131, nome: "Portal de Vampiro", tipo: "teleporte"},
];